### ISSUE TITLE
Uri-Host URI-Port (Klaus WGLC review 2/12/2019)

### ISSUE THREAD

**Issue by csosto-pk** [SanKumar2015/EST-coaps#135]
Klaus commented 
> "The Uri-Host and Uri-Port Options are optional." -- 
that 
> These options are not optional. They just can be encoded very efficiently (in 0 bytes) if they happen to have their default value.

Also he said about 
> They are usually omitted as the DTLS destination and port are sufficient." 

that 
>The default values of the options are the IP destination address and UDP port, respectively (in CoAP-over-UDP).

**Comment by csosto-pk** [comment]
Peter updated the text to now say 
>  The default URI-host and Uri-Port Options can be omitted.

**Comment by csosto-pk** [comment]
After asking Klaus offline 
> Do you mean conceptually that the options are processed by the receiver as if they existed? They won't exist in the COAP  message sent on the wire right?

he clarified that 
> Yes, exactly. I'd like to update RFC 7252 at some point and make it more clear when an option is logically present and when it is sent on the wire. Uri-Host and Uri-Port are logically always present in a request but aren't always sent on the wire (namely if and only if they have their default value).

So we need to update the text to not say that the Uri-Host and Port are optional, but that the do not need to be sent on the wire unless they do not coincide with the transport layer destination and port because the receiver will process them as such by default.

**Comment by petervanderstok** [comment]
What I did. See my textermPeterstokcons@bbhmail.nl   consultancy@vanderstok.org-------- Oorspronkelijk bericht --------Van: "Panos K." <notifications@github.com> Datum: 18-02-2019  16:41  (GMT+01:00) Aan: SanKumar2015/EST-coaps <EST-coaps@noreply.github.com> Cc: peter van der stok <consultancy@vanderstok.org>, Assign <assign@noreply.github.com> Onderwerp: Re: [SanKumar2015/EST-coaps] Uri-Host URI-Port (Klaus WGLC review
  2/12/2019) (#135) After asking Klaus offline

Do you mean conceptually that the options are processed by the receiver as if they existed? They won't exist in the COAP  message sent on the wire right?

he clarified that

Yes, exactly. I'd like to update RFC 7252 at some point and make it more clear when an option is logically present and when it is sent on the wire. Uri-Host and Uri-Port are logically always present in a request but aren't always sent on the wire (namely if and only if they have their default value).

So we need to update the text to not say that the Uri-Host and Port are optional, but that the do not need to be sent on the wire unless they do not coincide with the transport layer destination and port because the receiver will process them as such by default.

—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/SanKumar2015/EST-coaps","title":"SanKumar2015/EST-coaps","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/SanKumar2015/EST-coaps"}},"updates":{"snippets":[{"icon":"PERSON","message":"@csosto-pk in #135: After asking Klaus offline \r\n\u003e Do you mean conceptually that the options are processed by the receiver as if they existed? They won't exist in the COAP  message sent on the wire right?\r\n\r\nhe clarified that \r\n\u003e Yes, exactly. I'd like to update RFC 7252 at some point and make it more clear when an option is logically present and when it is sent on the wire. Uri-Host and Uri-Port are logically always present in a request but aren't always sent on the wire (namely if and only if they have their default value).\r\n\r\nSo we need to update the text to not say that the Uri-Host and Port are optional, but that the do not need to be sent on the wire unless they do not coincide with the transport layer destination and port because the receiver will process them as such by default. "}],"action":{"name":"View Issue","url":"https://github.com/SanKumar2015/EST-coaps/issues/135#issuecomment-464780400"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/SanKumar2015/EST-coaps/issues/135#issuecomment-464780400",
"url": "https://github.com/SanKumar2015/EST-coaps/issues/135#issuecomment-464780400",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by csosto-pk** [comment]
Addressed. Text now reads 
>The URI-host and Uri-Port Options can be omitted from the COAP message sent on the wire. When omitted, they are logically assumed to be the transport protocol destination address and port respectively. Explicit Uri-Host and Uri-Port Options are typically used when an endpoint hosts multiple virtual servers and uses the Options to route the requests accordingly. 

And 
> The Uri-Host and Uri-Port Options can be omitted if they coincide with the transport protocol destination address and port respectively. Explicit Uri-Host and Uri-Port Options are typically used when an endpoint hosts multiple virtual servers and uses the Options to route the requests accordingly.
